from arglex.Assessments import Assessments
from arglex.Authority import Authority
from arglex.Causation import Causation
from arglex.Conditionals import Conditionals
from arglex.Contrast import Contrast
from arglex.Difficulty import Difficulty
from arglex.Doubt import Doubt
from arglex.Emphasis import Emphasis
from arglex.Generalization import Generalization
from arglex.Inconsistency import Inconsistency
from arglex.Inyourshoes import Inyourshoes
from arglex.Necessity import Necessity
from arglex.Possibility import Possibility
from arglex.Priority import Priority
from arglex.Rhetoricalquestion import Rhetoricalquestion
from arglex.Structure import Structure
from arglex.Wants import Wants
from arglex.Priority import Priority
from arglex.Classifier import Classifier

